name: Code Linter

on:
  push:
    branches:
      - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  resharper-core-lint:
    # Name the Job
    name: Clean up C# code base via R# CLT
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    env:
      working-directory : ./

    steps:
      - uses: actions/checkout@v3

      - run: git pull

      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Setup ReSharper Command Line Tools
        run: dotnet tool install --global JetBrains.ReSharper.GlobalTools --version 2022.3

      # Building of the project is important step to resolve bin dependensies.
      # See docs https://www.jetbrains.com/help/resharper/CleanupCode.html#9663f16d
      - name: Build
        run: dotnet build --verbosity normal

      - name: Clean up codebase via ReSharper Command Line Tools
        run: jb cleanupcode --profile="Full Cleanup" CombatDicesTeam.Graphs.sln
        working-directory: ${{env.working-directory}}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "[Bot] Automated ReSharper CLT update"
          add: "*.cs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}