name: Mutation Tests using Stryker.NET

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'          # Run the workflow for all pull requests

jobs:

  test:
    
    name: Mutation Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OUTPUT: 1

    steps:
    - uses: actions/checkout@v3

    # Install the .NET SDK indicated in the global.json file
    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --verbosity normal

    - name: Setup Stryker
      run: dotnet tool install -g dotnet-stryker --version 3.7

    - name: Kill the mutants!
      run: dotnet stryker --reporter "cleartexttree"